//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimTakipSistemi
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Panel pnlHata;
        protected global::System.Web.UI.WebControls.Literal litHata;
        protected global::System.Web.UI.WebControls.TextBox txtKullaniciAdi;
        protected global::System.Web.UI.WebControls.TextBox txtSifre;
        protected global::System.Web.UI.WebControls.Button btnGiris;
    }
}